#lang sicp

;Exercise 1.14.  Draw the tree illustrating the process generated by the count-change procedure of section 1.2.2 in making change for 11 cents. What are the orders of growth of the space and number of steps used by this process as the amount to be changed increases?

(define (count-change amount)
  (cc amount 5))
(define (cc amount kinds-of-coins)
  (cond ((= amount 0) 1)
        ((or (< amount 0) (= kinds-of-coins 0)) 0)
        (else (+ (cc amount
                     (- kinds-of-coins 1))
                 (cc (- amount
                        (first-denomination kinds-of-coins))
                     kinds-of-coins)))))
(define (first-denomination kinds-of-coins)
  (cond ((= kinds-of-coins 1) 1)
        ((= kinds-of-coins 2) 5)
        ((= kinds-of-coins 3) 10)
        ((= kinds-of-coins 4) 25)
        ((= kinds-of-coins 5) 50)))

(count-change 11)
; 4 
; see 1.14a

; how does space and steps change as amount changes?
; see 1.14b
; space is O(n) because each brach? of tree is max depth n
; note: each new "amount" is still stored, because it needs to be used for the next cc call too
; steps is O(n^5) because for (cc n 5) it will (for large n) be n/50 times of (cc n 4), n/50 times of n/25 times of (cc n 3), etc... 
