#lang sicp

;Exercise 1.9.  Each of the following two procedures defines a method for adding two positive integers in terms of the procedures inc, which increments its argument by 1, and dec, which decrements its argument by 1.
;Using the substitution model, illustrate the process generated by each procedure in evaluating (+ 4 5). Are these processes iterative or recursive?

(define (+ a b)
  (if (= a 0)
      b
      (inc (+ (dec a) b))))
; this is the iterative version
; (+ a=4 b=5)
; (= a=4 0) ;#f 
; (inc (+ a=3 b=5))
; (= a=3 0) ;#f
; (inc ((inc (+ a=2 b=5))))
; (= a=2 0) ;#f
; (inc (inc ((inc (+ a=1 b=5)))))
; (= a=1 0) ;#f
; (inc (inc (inc ((inc (+ a=0 b=5))))))
; (= a=0 0) ;#t
; (inc (inc (inc ((inc 5)))))
; 9


(define (+ a b)
  (if (= a 0)
      b
      (+ (dec a) (inc b))))
; this is the recursive version
; (+ a=4 b=5)
; (= a=4 0) ;#f
; (+ a=3 b=6)
; (= a=3 0) ;#f
; (+ a=2 b=7)
; (= a=2 0) ;#f
; (+ a=1 b=8)
; (= a=1 0) ;#f
; (+ a=0 b=9)
; (= a=0 0) ;#t
; 9
